# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-Session
version:      1.26
version_from: lib/CGI/Builder/Session.pm
installdirs:  site
requires:
    CGI::Builder:                  1.2
    CGI::Session:                  3.95
    File::Spec:                    0
    Object::groups:                1.62
    Object::props:                 1.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
